repos:
- repo: git://github.com/dnephin/pre-commit-golang
  rev: 9d1819b279facd713d6b9dc177a71a80b00e96dd
  hooks:
    - id: go-fmt
    - id: go-vet
    - id: go-lint
    - id: go-imports
    - id: go-cyclo
      args: [-over=15]
    - id: validate-toml
    - id: no-go-testing
    - id: go-unit-tests
    - id: go-build
    - id: go-mod-tidy
