repos:
- repo: git://github.com/dnephin/pre-commit-golang
  rev: 9d1819b279facd713d6b9dc177a71a80b00e96dd
  hooks:
    - id: go-fmt
    - id: go-vet
    - id: go-lint
    - id: go-imports
    - id: go-cyclo
      args: [-over=15]
    - id: go-unit-tests
    - id: go-build
    - id: go-mod-tidy

- repo: git://github.com/codespell-project/codespell
  rev: b2e96b267e965ea09423c05c98a9f13884bfb116
  hooks:
    - id: codespell
