---
projectID: amb1s1
instanceName: test2
zone: us-central1-a
machineType: c2-standard-4
diskSize: 10
publicKeyPath: /home/gomdavid/.ssh/rsa.pub
privateKeyPath: /home/gomdavid/.ssh/rsa
sshKeyUsername: gomdavid
customImageName: test-eve-ng
