---
projectID: amb1s1
instanceName: test2
zone: us-central1-a
machineType: c2-standard-4
diskSize: 10
sshPublicKeyFileName: /home/gomdavid/.ssh/rsa.pub
sshPrivateKeyFileName: /home/gomdavid/.ssh/rsa
sshKeyUsername: gomdavid
customEveNGImageName: test-eve-ng
